# Generated by Django 5.2.5 on 2025-08-23 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('etat', models.CharField(default='Non restitué', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('est_perdu', models.BooleanField(default=True)),
                ('lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('citoyen', models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.objet')),
            ],
        ),
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_restitution', models.DateField(auto_now_add=True)),
                ('heure_restitution', models.TimeField(auto_now_add=True)),
                ('citoyen', models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commissariat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.commissariat')),
                ('objet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.objet')),
                ('policier', models.ForeignKey(limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policier_restitutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
