# Generated by Django 5.2.6 on 2025-11-02 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_alter_message_expediteur_alter_message_reponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'objet")),
                ('description', models.TextField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('perdu', 'Perdu'), ('trouve', 'Trouvé'), ('reclame', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], default='perdu', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='objets/')),
                ('code_unique', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='declarations/')),
                ('etat_initial', models.CharField(choices=[('perdu', 'Perdu'), ('trouve', 'Trouvé'), ('reclame', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], max_length=20)),
                ('type_declaration', models.CharField(choices=[('perdu', 'Objet perdu'), ('trouve', 'Objet trouvé')], max_length=10)),
                ('citoyen', models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Citoyen déclarant')),
                ('reclame_par', models.ManyToManyField(blank=True, limit_choices_to={'role': 'citoyen'}, related_name='objets_reclames', to=settings.AUTH_USER_MODEL, verbose_name='Réclamé par')),
                ('trouve_par', models.ManyToManyField(blank=True, limit_choices_to={'role': 'citoyen'}, related_name='objets_trouves', to=settings.AUTH_USER_MODEL, verbose_name='Trouvé par')),
                ('objet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='objets.objet')),
            ],
        ),
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_restitution', models.DateField(default=django.utils.timezone.now)),
                ('heure_restitution', models.TimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('effectuee', 'Effectuée')], default='planifiee', max_length=20)),
                ('citoyen', models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citoyen_restitutions', to=settings.AUTH_USER_MODEL)),
                ('commissariat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.commissariat')),
                ('objet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restitutions', to='objets.objet')),
                ('policier', models.ForeignKey(limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policier_restitutions', to=settings.AUTH_USER_MODEL)),
                ('restitue_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restitution',
                'verbose_name_plural': 'Restitutions',
                'ordering': ['-date_restitution', '-heure_restitution'],
            },
        ),
    ]
