# Generated by Django 5.2.5 on 2025-08-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='declarations/'),
        ),
    ]
