# Generated by Django 5.2.4 on 2025-08-26 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0002_declaration_description_declaration_image'),
        ('users', '0002_alter_utilisateur_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='citoyen',
            field=models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_declaration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='est_perdu',
            field=models.BooleanField(default=True, verbose_name='Est-ce un objet perdu ?'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='declarations/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.objet', verbose_name='Objet déclaré'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('retrouvé', 'Retrouvé'), ('restitué', 'Restitué')], default='perdu', max_length=50, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'objet"),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='citoyen',
            field=models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citoyen_restitutions', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='commissariat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.commissariat', verbose_name='Commissariat'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='date_restitution',
            field=models.DateField(auto_now_add=True, verbose_name='Date de restitution'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='heure_restitution',
            field=models.TimeField(auto_now_add=True, verbose_name='Heure de restitution'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.objet', verbose_name='Objet restitué'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='policier',
            field=models.ForeignKey(limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policier_restitutions', to=settings.AUTH_USER_MODEL, verbose_name='Policier'),
        ),
    ]
