# Generated by Django 5.2.5 on 2025-08-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0003_alter_declaration_citoyen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='code_unique',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code unique'),
        ),
    ]
