# Generated by Django 5.2.4 on 2025-08-30 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0004_objet_code_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='reclame_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_reclames', to=settings.AUTH_USER_MODEL, verbose_name='Réclamé par'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='trouve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_trouves', to=settings.AUTH_USER_MODEL, verbose_name='Trouvé par'),
        ),
    ]
