# Generated by Django 5.2.4 on 2025-09-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0005_declaration_reclame_par_declaration_trouve_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='est_perdu',
        ),
    ]
