# Generated by Django 5.2.4 on 2025-09-06 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0006_remove_declaration_est_perdu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restitution',
            options={'ordering': ['-date_restitution', '-heure_restitution'], 'verbose_name': 'Restitution', 'verbose_name_plural': 'Restitutions'},
        ),
        migrations.AddField(
            model_name='restitution',
            name='restitué_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Restitué par'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='policier',
            field=models.ForeignKey(limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policier_restitutions', to=settings.AUTH_USER_MODEL, verbose_name='Policier planificateur'),
        ),
    ]
