# Generated by Django 5.2.4 on 2025-09-06 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0007_alter_restitution_options_restitution_restitué_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restitution',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restitutions', to='objets.objet', verbose_name='Objet restitué'),
        ),
    ]
