# Generated by Django 5.2.6 on 2025-09-20 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0008_alter_restitution_objet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='restitution',
            old_name='restitué_par',
            new_name='restitue_par',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='trouve_par',
        ),
        migrations.AddField(
            model_name='declaration',
            name='trouve_par',
            field=models.ManyToManyField(blank=True, related_name='objets_trouves', to=settings.AUTH_USER_MODEL, verbose_name='Trouvé par'),
        ),
    ]
