# Generated by Django 5.2.6 on 2025-09-22 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0009_rename_restitué_par_restitution_restitue_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('effectuee', 'Effectuée')], default='planifiee', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_declaration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de déclaration'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='reclame_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_reclames', to=settings.AUTH_USER_MODEL, verbose_name='Réclamé par'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='trouve_par',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'citoyen'}, related_name='objets_trouves', to=settings.AUTH_USER_MODEL, verbose_name='Trouvé par'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('retrouvé', 'Retrouvé'), ('reclamé', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], default='perdu', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='date_restitution',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de restitution'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='heure_restitution',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure de restitution'),
        ),
    ]
