# Generated by Django 5.2.6 on 2025-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0011_alter_objet_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouvé', 'Trouvé'), ('reclamé', 'Réclamé'), ('en_attente', 'En_attente'), ('restitue', 'Restitué')], default='perdu', max_length=20, verbose_name='État'),
        ),
    ]
