# Generated by Django 5.2.6 on 2025-09-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0012_alter_objet_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objets/', verbose_name="Image de l'objet"),
        ),
        migrations.AlterField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouvé', 'Trouvé'), ('reclamé', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], default='perdu', max_length=20, verbose_name='État'),
        ),
    ]
