# Generated by Django 5.2.6 on 2025-10-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0013_objet_image_alter_objet_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='etat_initial',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouvé', 'Trouvé'), ('reclamé', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], default='perdu', max_length=20, verbose_name='État initial'),
        ),
    ]
