# Generated by Django 5.2.6 on 2025-10-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0014_declaration_etat_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='reclame_par',
        ),
        migrations.AddField(
            model_name='declaration',
            name='reclames_par',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'citoyen'}, related_name='objets_reclames', to=settings.AUTH_USER_MODEL, verbose_name='Réclamé par'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='objets.objet', verbose_name='Objet déclaré'),
        ),
    ]
