# Generated by Django 5.2.6 on 2025-10-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0015_remove_declaration_reclame_par_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='reclames_par',
            new_name='reclame_par',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.objet', verbose_name='Objet déclaré'),
        ),
    ]
