# Generated by Django 5.2.6 on 2025-10-24 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0016_rename_reclames_par_declaration_reclame_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='trouve_par',
        ),
        migrations.AddField(
            model_name='declaration',
            name='trouve_egalement_par',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'citoyen'}, related_name='objets_trouves_egalement', to=settings.AUTH_USER_MODEL, verbose_name='Aussi trouvé par'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='citoyen',
            field=models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Citoyen déclarant'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='etat_initial',
            field=models.CharField(choices=[('PERDU', 'Perdu'), ('TROUVE', 'Trouvé')], default='PERDU', max_length=20, verbose_name='Type de déclaration'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.objet', verbose_name='Objet concerné'),
        ),
    ]
