# Generated by Django 5.2.6 on 2025-10-24 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0017_remove_declaration_trouve_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='trouve_egalement_par',
        ),
        migrations.AddField(
            model_name='declaration',
            name='trouve_par',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'citoyen'}, related_name='objets_trouves', to=settings.AUTH_USER_MODEL, verbose_name='Trouvé par'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='citoyen',
            field=models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='etat_initial',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouvé', 'Trouvé'), ('reclamé', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], default='perdu', max_length=20, verbose_name='État initial'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.objet', verbose_name='Objet déclaré'),
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='reclame_par',
        ),
        migrations.AddField(
            model_name='declaration',
            name='reclame_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_reclames', to=settings.AUTH_USER_MODEL, verbose_name='Réclamé par'),
        ),
    ]
