# Generated by Django 5.2.6 on 2025-10-24 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0018_remove_declaration_trouve_egalement_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='reclame_par',
        ),
        migrations.AddField(
            model_name='declaration',
            name='reclame_par',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'citoyen'}, related_name='objets_reclames', to=settings.AUTH_USER_MODEL, verbose_name='Réclamé par'),
        ),
    ]
