# Generated by Django 5.2.6 on 2025-10-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0019_remove_declaration_reclame_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='type_declaration',
            field=models.CharField(choices=[('perdu', 'Objet perdu'), ('trouve', 'Objet trouvé')], default=1, max_length=10, verbose_name='Type de déclaration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declaration',
            name='etat_initial',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouvé', 'Trouvé'), ('reclamé', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], max_length=20, verbose_name='État initial'),
        ),
    ]
