# Generated by Django 5.2.6 on 2025-10-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0020_declaration_type_declaration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations_trouvees', to='objets.objet', verbose_name='Objet déclaré'),
        ),
    ]
