# Generated by Django 5.2.6 on 2025-10-26 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets', '0021_alter_declaration_objet'),
        ('users', '0011_alter_message_expediteur_alter_message_reponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='citoyen',
            field=models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Citoyen déclarant'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_declaration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='etat_initial',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouve', 'Trouvé'), ('reclame', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], max_length=20),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='declarations/'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='objets.objet'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='type_declaration',
            field=models.CharField(choices=[('perdu', 'Objet perdu'), ('trouve', 'Objet trouvé')], max_length=10),
        ),
        migrations.AlterField(
            model_name='objet',
            name='code_unique',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='objet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouve', 'Trouvé'), ('reclame', 'Réclamé'), ('en_attente', 'En attente'), ('restitue', 'Restitué')], default='perdu', max_length=20),
        ),
        migrations.AlterField(
            model_name='objet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objets/'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='citoyen',
            field=models.ForeignKey(limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citoyen_restitutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='commissariat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.commissariat'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='date_restitution',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='heure_restitution',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restitutions', to='objets.objet'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='policier',
            field=models.ForeignKey(limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policier_restitutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='restitue_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'policier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('effectuee', 'Effectuée')], default='planifiee', max_length=20),
        ),
    ]
