# Generated by Django 5.2.4 on 2025-09-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_utilisateur_commissariat_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('policier', 'Policier'), ('citoyen', 'Citoyen')], default='policier', max_length=20),
        ),
    ]
