# Generated by Django 5.2.6 on 2025-09-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default='photos_profil/default-avatar.png', null=True, upload_to='photos_profil/'),
        ),
    ]
