# Generated by Django 5.2.6 on 2025-10-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_banni',
            field=models.BooleanField(default=False),
        ),
    ]
