# Generated by Django 5.2.6 on 2025-10-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_utilisateur_est_banni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('policier', 'Policier'), ('citoyen', 'Citoyen')], default='admin', max_length=20),
        ),
    ]
