# Generated by Django 5.2.6 on 2025-10-23 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('reponse', models.TextField(blank=True, null=True, verbose_name="Réponse de l'administrateur")),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message citoyen',
                'verbose_name_plural': 'Messages citoyens',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
