# Generated by Django 5.2.6 on 2025-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_message_expediteur_alter_message_reponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('policier', 'Policier'), ('citoyen', 'Citoyen')], default='admin', max_length=20),
        ),
    ]
